# Build Configuration for Travis CI
# https://travis-ci.org

dist: trusty
sudo: required
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'sourceline: 'ppa:mhier/libboost-latest'']
          packages: ['g++-4.9', 'boost']
      env: COMPILER=g++-4.9

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
